### PR TITLE
Added package outlines to F.Fab layer

### PR DESCRIPTION
**Pull request by SchrodingersGat**
* Added the package dimensions to the F.Fab layer for multiple SOIC footprints
* Added the W suffix to SOIC-16W

### CODE REVIEW

**Comment by greenscreenflicker** [comment]
@SchrodingersGat: Thanks for renaming.

**Comment by SchrodingersGat** [comment]
In addition to adding package outlines, this PR now also fixes the Silk-screen issue as discussed in https://github.com/KiCad/Housings_SOIC.pretty/issues/10

Example:
eg

**Comment by SchrodingersGat** [comment]
As per https://github.com/KiCad/Housings_SSOP.pretty/pull/12 the F.Fab layer now has circular pin-1 indication

**Comment by SchrodingersGat** [comment]
@pointhi  @CarlPoirier  same changes applied here

**Comment by CarlPoirier** [comment]
Thank you very much.

**Pull request merged**
