### PR TITLE
Add stretched soic

### PR DESCRIPTION
**Pull request by jkriege2**
Added two stretched SSOIC--packages iwth 6 and 8 pins:

2017-05-15 23_13_35-footprint editor no active library
2017-05-15 23_03_30-footprint editor no active library

references:
https://docs.broadcom.com/cs/Satellite?blobcol=urldata&blobheader=application%2Fpdf&blobheadername1=Content-Disposition&blobheadername2=Content-Type&blobheadername3=MDT-Type&blobheadervalue1=attachment%3Bfilename%3DAV02-2928EN_DS_ACPL-x343_2017-04-28.pdf&blobheadervalue2=application%2Fx-download&blobheadervalue3=abinary%253B%2Bcharset%253DUTF-8&blobkey=id&blobnocache=true&blobtable=MungoBlobs&blobwhere=1430896950891&ssbinary=true
https://docs.broadcom.com/cs/Satellite?blobcol=urldata&blobheader=application%2Fpdf&blobheadername1=Content-Disposition&blobheadername2=Content-Type&blobheadername3=MDT-Type&blobheadervalue1=attachment%3Bfilename%3DAV02-2460EN_DS_ACPL-C79x_2015-10-23.pdf&blobheadervalue2=application%2Fx-download&blobheadervalue3=abinary%253B%2Bcharset%253DUTF-8&blobkey=id&blobnocache=true&blobtable=MungoBlobs&blobwhere=1430873351268&ssbinary=true

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
I'm not a fan of the pins being drawn on Fab layer (and especially not for one but not the other). Please remove these for consistency :)

**Comment by jkriege2** [comment]
Hi!

just an outdated screenshot ...a ctually looks like this:
2017-05-16 09_35_47-footprint editor no active library

I was thinking a bit ... maybe we should indictae the pin-end-distance in the filename (such as for the DIP-packages with `_W...mm` ... if you look at the packages, the pin distance is quite different, although the body has the same size!

What do you think? If yes, I can do the changes this evening!

BEst,
JAN

**Comment by jkriege2** [comment]
Hi!

OK, I'll have to work a bit more on this ... will reopen, when done!

**Comment by jkriege2** [comment]
OK, I reworked the footpritns now ... and completed the whole series:

2017-05-16 20_41_20-pcbnew d__temp_testtemp_testtemp kicad_pcb

This should cover most optocouplers in SMD that are out there (I hope). References:
- http://datasheet.octopart.com/OPIA403BTRE-Optek-datasheet-5328560.pdf
- https://docs.broadcom.com/cs/Satellite?blobcol=urldata&blobheader=application%2Fpdf&blobheadername1=Content-Disposition&blobheadername2=Content-Type&blobheadername3=MDT-Type&blobheadervalue1=attachment%3Bfilename%3DIPD-Selection-Guide_AV00-0254EN_030617.pdf&blobheadervalue2=application%2Fx-download&blobheadervalue3=abinary%253B%2Bcharset%253DUTF-8&blobkey=id&blobnocache=true&blobtable=MungoBlobs&blobwhere=1430884105675&ssbinary=true
- https://www.elpro.org/de/index.php?controller=attachment&id_attachment=339

Best,
JAN

**Comment by SchrodingersGat** [comment]
@jkriege2 is the `Clearance` measurement here the distance between the end of the pads? Perhaps there is a more concise way of saying this e.g. `W` as you suggest previously.

**Comment by jkriege2** [comment]
Hi!

yes, it's the approx. inner distance between the pins.  Most of these packages are meant for optocouplers and I took the wording from one of the datasheets (I think Avago). Maybe `Isolation` is clearer? Any other ideas?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Hi Jan,

Finally had a chance to look at these.

1. I like SSO better than StretchedSO. You can still have StretchedSO in the description for the footprint but I think it makes the filename too long. Many of the datasheets use SSO nomenclature so I think that should be ok.

2. Clearance is probably the best naming scheme for distance between pins.

**Comment by SchrodingersGat** [comment]
Thanks!

**Pull request merged**
