### PR TITLE
Added the footprint of the Toshiba optocoupler TLP2770

### PR DESCRIPTION
**Pull request by Misca1234**
Adding the component Toshiba TLP2770 
Housings_SOIC     https://github.com/KiCad/Housings_SOIC.pretty/pull/20
kicad-library         https://github.com/KiCad/kicad-library/pull/1281
3D model             https://github.com/KiCad/packages3D/pull/60

### CODE REVIEW

**Comment by Misca1234** [comment]
Adding the component Toshiba TLP2770 
Housings_SOIC     https://github.com/KiCad/Housings_SOIC.pretty/pull/20
kicad-library         https://github.com/KiCad/kicad-library/pull/1281
3D model             https://github.com/KiCad/packages3D/pull/60

bild

bild

bild

**Comment by poeschlr** [comment]
Why is a short line segment on the courtyard layer near pin 1?

Please include a part outline on the silk layer such that it is visible after assembly. (I would simply copy the top and bottom line of the fab layer, move them 0.1 mm towards the outside and change the layer of this new line to silk as well as changing the line width to 0.12)

Add pin 1 markers on the fab and silk layers. 
  - On the fab layer simply add a chamfer to the corner near pin 1
  - On silk: Make the top line i suggested you create a bit longer on the left side. (With a bit i mean make it such that it runs alongside the pad 1 for the full lenght of this pad.)

**Comment by Misca1234** [comment]
> Why is a short line segment on the courtyard layer near pin 1?
According to 
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention 
chapter 7. General Rules for Footprints, 4.iii
it should be there 

I add the silk screen as well

**Comment by poeschlr** [comment]
Rule 7.4.iii talks about the second reference.
Did you mean 7.4.i? The pin 1 marker. It should be on the fabrication layer not on the courtyard layer.

What is the purpose of the different layers in kicad:
  - Copper layers: (F.Cu, B.Cu, In1.Cu,...) Contain all copper features. Footprints should not include anything on these layers. (Except pads of course.)
  - Adhesive and paste layers should also be only used in pads (These define where the board assembler will place solder paste or glue)
  - Mask layer: This layer is the inverse of the solder mask. (The electrically insulating stuff that gets applied over the whole board.)
  - The cmts, dwgs and eco layers are for the use by the user. They are normally not used for footprints
  - Edge cuts: this layer defines the board outline. It should not be used for footprints.
  - Margin: only a graphical layer. Not really used for anything
  - Courtyard: for footprints only. This layer consists of a closed outline of the area that is needed for the part itself plus a bit more for the pick and place robot (or for your tools if you hand solder the board)
  - Fab layer: Fabrication documentation. This layer is used for documenting the pcb. It has all informations on it that are needed to assemble the board. (Part outline, Pin 1 marker, Reference and Value)
  - Silk layer: This is the stuff that gets printed on the pcb. We try to have it designed in such a way that everything on it is still visible after the component is assembled. (SMD components should not have anything below the component because this could create problems in the reflow process. For some THT components it makes sense to have artwork below the part that aids in the manual assembly of the pcb.)

**Comment by Misca1234** [comment]
> Rule 7.4.iii talks about the second reference.
> Did you mean 7.4.i? The pin 1 marker. It should be on the fabrication layer not on the courtyard layer.

No the chapter 7.iii describe the F.Fab layer and on the provided image there is a line next to pin 1

**Comment by poeschlr** [comment]
This line is on the silk screen (If you mean the greenish line.)

**Comment by Misca1234** [comment]
It looks like this now 
bild

**Comment by Misca1234** [comment]
bild

**Comment by poeschlr** [comment]
I would make it more like this:
screenshot from 2017-06-04 15-45-45
The file i created (as .txt because github does not allow kicad_mod files. Just remove the .txt ending to few it in kicad.)
[SO-6L_10x3.84mm_Pitch1.27mm.kicad_mod.txt](https://github.com/KiCad/Housings_SOIC.pretty/files/1050356/SO-6L_10x3.84mm_Pitch1.27mm.kicad_mod.txt)

**Comment by Misca1234** [comment]
I pasted in your txt file

**Comment by poeschlr** [comment]
I exported the file from the footprint library editor. This is why travis now complains about wrong module name.

If you want to use this file do the following. (I did not know this until i saw it here. If i would have known this, i would have mentioned it.)
  1. open footprint editor
  1. Set active library to be the Housings_SOIC lib
  1. use the import button (top toolbar) to import the footprint
  1. Save the footprint again.

It could be that simply opening the footprint in the editor and re saving it fixes the problem as well.

**Comment by Misca1234** [comment]
Mmm, i saw the difference in my editor but guessed it was correct, I re push it

**Comment by poeschlr** [comment]
I had another detailed look.

Move the silk screen back out such that it is completely outside the rectangle on the fab layer. (Like i had it)

The courtyard is not symetrical at the moment. Move it by 0.02mm towards the bottom. (resulting y coordinate = 2.17 for the top and bottom lines) In x direction it should result in 5.65 (currently 5.66 and 5.64 so again move by 0.01) you can use ctrl+m for that.

Add a link to the datasheet to the documentation field. (Such that users know where you got the measurements for the footprint)

**Comment by Misca1234** [comment]
Here you go

**Comment by poeschlr** [comment]
There seems to be a misunderstanding.

The "rectangle" on the fab layer has been correct. (in the y direction, i would never have noticed that the x direction is not quite right if i would not have checked it now that i wanted to give you more details.)

The outline on fab should represent the outline of the package as defined in the datasheet. 
In this case: 7.5x3.84mm which means each corner (except the one with the chamfer) has the absolute coordinates (3.75, 1.92)
Currently you have (3.7, 1.8) which results in a part size of 7.4x3.6mm

The courtyard is also not quite right. As i said above each corner should have the absolute coordinates (5.65, 2.17)
Currently they have (5.6, 2.2) This means the clearance in the x direction is only 0.2mm instead of 0.25!

(Yes i know i am a bit pedantic here. I hope you don't take it personally.)

**Comment by Misca1234** [comment]
No, np, i fix it tomrrow

**Comment by Misca1234** [comment]
Now it should be correct

**Comment by Misca1234** [comment]
This model need the SO-6L mode in 
https://github.com/easyw/kicad-3d-models-in-freecad/pull/68

**Comment by poeschlr** [comment]
Looks good. Thanks for your contribution.

**Pull request merged**
