### PR TITLE
Vishay PowerPAK SO-8 single and dual

### PR DESCRIPTION
**Pull request by evanshultz**
Working on updating and moving footprints from SMD_Packages as mentioned at https://github.com/KiCad/SMD_Packages.pretty/issues/20.

Documents:
https://www.vishay.com/docs/71655/powerpak.pdf
https://www.vishay.com/docs/72599/72599.pdf
https://www.vishay.com/docs/72600/72600.pdf

Image:
image

### CODE REVIEW

**Comment by poeschlr** [comment]
The pdf link for the dual landing pattern does not work. (Missing '0')
correct would be: https://www.vishay.com/docs/72600/72600.pdf

The position of the large pad (or pads) in x direction is off by 0.02mm for both packages.
screenshot from 2017-08-21 09-28-43

**Comment by evanshultz** [comment]
@poeschlr Thanks! Not sure how I missed that, but all looks good now.

BTW, how do you generate the dimensioned drawing above? Is there an automatic way to do it?

**Comment by poeschlr** [comment]
I use kicad stepup to import the footprint into freecad and then the drawing dimensions workbench for the dimensioning.
Sadly with the current stepup script one can not import fab and courtyard layers. Maybe @easyw can add such a feature. But until then i just move the interesting stuff over to the silk layer and import it this way. (This means i temporarily remove the silk outline and move the fab outline and courtyard to silk. At least if i am interested in this stuff. For this footprint i only looked at the pads.)

**Comment by evanshultz** [comment]
@poeschlr I see. Thank you. Can this PR be merged?

**Comment by poeschlr** [comment]
I have overlooked a problem. The outer pads have the wrong y coordinate (pin pitch is only correct between the middle two pads.)
screenshot from 2017-08-21 21-35-41
Same for the single pad version. (Here i used different measurements)
screenshot from 2017-08-21 21-40-51

**Comment by evanshultz** [comment]
@poeschlr What was I doing? 0.66mm / 2 + 1.27mm is 1.905mm pad centers. I had 1.855mm. Fixed now.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
