### PR TITLE
[add] Footprints similar to SO-4 for solid state relays

### PR DESCRIPTION
**Pull request by poeschlr**
Because of a request on the forum (and challenge by @Shackmeister) i'm suggesting to add these two footprints used in solid state relays.
Datasheet for ASSR relay (SO-4_4.4x4.3mm) https://docs.broadcom.com/docs/AV02-0173EN
Datasheet CPC1017N http://www.ixysic.com/home/pdfs.nsf/www/CPC1017N.pdf/$file/CPC1017N.pdf
Both of them are similar to the existing SO-4 footprints.

The ASSR footprint is called SO-4 in the datasheet for this reason i named it SO-4 here as well.
The CPC footprint seems to be specialized for this one devise. (At least there is no reference in the datasheet to a standardized package name) For this reason i opted to name the footprint IXYS_CPC1017N
screenshot from 2017-07-02 22-32-18

I will commit specialized symbols as well.

### CODE REVIEW

**Comment by poeschlr** [comment]
Re reading the datasheet i now see the references to SOP-4 in the datasheet for the IXYS_CPC1017N.
>Small 4-Pin SOP Package

Now my question: Would this be named SOP-4_size_pitch

**Comment by poeschlr** [comment]
@SchrodingersGat could you take a look at this and help me decide how the footprint for the CPC1017N ssr should be called?
(And in which lib it should go. I think there are other footprints called SOP-* that are in the Housings_SSOP.pretty library. If you agree it should be called like i named it now, then it should probably move to the ssop lib.)

**Comment by SchrodingersGat** [comment]
I think the IXYS footprint is "generic" enough that we can use the standard naming e.g. `SOP_...`

The differences between SOIC / SOP / SSOP / etc are all quite vague really. Generally they refer to pitch spacing (as says Wikipedia) but manufacturers use them to mean different things, or add their own e.g. uSOIC and MSOP etc.

The KiCad library separation is a bit arbitrary in that regard, but as the datasheet says "SOP" then I'd say it should go in the [Housings_SSOP library](https://github.com/KiCad/Housings_SSOP.pretty)

**Comment by evanshultz** [comment]
@poeschlr Will you be moving these footprints so another repo, then?

**Comment by poeschlr** [comment]
It seems i missed your answer @SchrodingersGat (Somehow it got lost in all the notifications i get from github.)
I moved the sop footprint over to the ssop library. new PR: https://github.com/KiCad/Housings_SSOP.pretty/pull/35

**Comment by SchrodingersGat** [comment]
@poeschlr no worries - are you going to close this one then?

**Comment by poeschlr** [comment]
@SchrodingersGat This one has the second footprint in it (SO-4)
Which should be ok here. (Unless all SO-4 footprints are in the wrong library)

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
