### PR TITLE
Add DSO-8 footprint

### PR DESCRIPTION
**Pull request by hackscribble**
Similar to SOIC-8 but smaller pin pads and larger exposed pad.

image

Datasheet:
http://www.infineon.com/cms/en/product/packages/PG-DSO/PG-DSO-8-43/

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@hackscribble is this footprint specific to Infineon?

If it is, it should be named as per [KLC Rule 6](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention#6-footprint-naming-conventions)

`Infineon_PG-DSO-8-43`

**Comment by hackscribble** [comment]
You are right, it is specific as far as I can tell @SchrodingersGat 

I will update this PR and the related symbol one.

**Comment by SchrodingersGat** [comment]
3D model name needs a small tweak - https://travis-ci.org/KiCad/Housings_SOIC.pretty/builds/227845610?utm_source=github_status&utm_medium=notification

**Comment by hackscribble** [comment]
PR updated.

**Comment by hackscribble** [comment]
Done properly now, I hope :blush:

**Comment by SchrodingersGat** [comment]
Thanks for the contribution

**Pull request merged**
