### PR TITLE
Create SO-8_5.3x6.2mm_Pitch1.27mm

### PR DESCRIPTION
**Pull request by evanshultz**
As requested and promised to @jkriege2 at https://github.com/KiCad/kicad-library/pull/1511.

Datasheet: http://www.ti.com.cn/cn/lit/ds/symlink/tl7705a.pdf

Image:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
@jkriege2 Could you take a look? Should be quick and you pointed out this new package in my PR I referenced above.

**Comment by jkriege2** [comment]
Hi!
looks good, except the courtyard clearance: Top-Bottom seems to be 0.3mm and left/right 0.15mm ... but it should be 0.25mm everyhwere ... Could you correct that? Then I can merge!

thanks,
JAN

**Comment by evanshultz** [comment]
@jkriege2 Hmm. That may mean the original SO-8 footprint has similar issues (at least on the top) since I used "Move Exactly" to grow that one. Anyway, done now. Thank you!

**Comment by jkriege2** [comment]
Thanks ...

at least SOIC-8 looks fine to me ... same for SOIJ-8 and SSO-8 ... btw. the check-scripts have an option that draws the courtyard for you ... and with the correct clearance base on the symbol size as in KLC ... see `check_kicad_mod.py --fixmore`

**Pull request merged**
