### PR TITLE
Create SOIC-14W_7.5x9.0mm_Pitch1.27mm and ST_PowerSO-20

### PR DESCRIPTION
**Pull request by evanshultz**
When overhauling the audio library (https://github.com/KiCad/kicad-library/pull/1560), a few footprints were missing. Here they are!

Documents:
- http://www.ti.com/lit/ds/symlink/lm1877.pdf
- http://www.st.com/resource/en/datasheet/tda7266d.pdf
- www.st.com/resource/en/application_note/cd00003801.pdf

Image:
image

Two questions about the ST package:
1. Even with a vendor-specific package, I think we should have dimensions. That makes the part easier to identify just looking at the footprint name. Yes?
1. This package is JEDEC MO-166, but I don't have that spec and so I'm not sure if there are multiple versions (no slug, slug up, slug down). Should I suffix this one `_SlugDown` to be safe?
1. ST gives no recommendation (I can find) about paste on pin 31. Suggestions?

### CODE REVIEW

**Comment by evanshultz** [comment]
While I still can't find JEDEC MO-166 online, many vendors use this PowerSO-20 package, being a JEDEC standard, and slug up is a viable option. PowerSO may be a ST-specific name, though. I see the term `HSOP` being used - I propose using `HSOP-20-1EP_11.0x15.9mm_Pitch1.27mm_SlugDown`? OK?

Docs:
- http://www.nxp.com/docs/en/application-note/AN2388.pdf
- http://pdf2.solecsy.com/421/735235b1-12bd-4e04-8310-28d8a9496302.pdf
- https://www.apexanalog.com/resources/quality/Apex-Package-Marking.pdf
- http://www.analog.com/media/en/technical-documentation/data-sheets/ADA4870.pdf
- https://www.apexanalog.com/resources/appnotes/an23u.pdf

**Comment by jkriege2** [comment]
- SOIC-14W looks fine.
- `HSOP-20-1EP_11.0x15.9mm_Pitch1.27mm_SlugDown` is OK, I think ... but I would then move it to https://github.com/KiCad/Housings_SSOP.pretty ... Also adding a variant with vias for heat-transfer and a bottom pad would be a great addition (see NXP AN).

Best,
JAN

**Comment by evanshultz** [comment]
@jkriege2 Thanks for looking! I think it's good now.

`PowerSO-20` renamed to `HSOP-20-1EP_11.0x15.9mm_Pitch1.27mm_SlugDown` and I also added `HSOP-20-1EP_11.0x15.9mm_Pitch1.27mm_SlugDown_ThermalVias` and `HSOP-20-1EP_11.0x15.9mm_Pitch1.27mm_SlugUp`. Image:
image

Oliver mentioned that SOIC vs SSOP is based on lead pitch. This HSOP part has 1.27mm pitch which means it goes into the SOIC library. It may be arbitrary, but that's why I put it here.

**Comment by evanshultz** [comment]
Since I'm here, I might as well do the 36 pin version. Will post it shortly.

**Comment by evanshultz** [comment]
Sorry. The 26 pin version is 0.65mm pitch, so it belongs in the SSOP repo.

@jkriege2 This PR is good to go.

**Comment by jkriege2** [comment]
I think you will need a bottom pad connecting all the thermal vias ... Could you add it?

**Comment by evanshultz** [comment]
I'm not able to find it quickly, but I've seen this discussed a couple times and the decision was to leave off bottom copper. At least at that time it was the decision. The user can add it if they want, but it's optional as part of the footprint. Could be big, could be small, etc.

**Comment by jkriege2** [comment]
I think it should be there, as the vias doe not make too much sense if there is no copper (where should the head be conducted/spread to? the PCB material does not conduct heat very well ... but copper does ;-)). I think the copper that should be there does not have to be as large as the upper one, but it should connect all vias. The user can then easily extend it if he wants and if he doesn't need the vias at all ... there's a variant footprint for that. We have such bottom copper for several packages with thermal vias (see e.g. the HTSSOPs in Housings_SSOP).

cu
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat Comment/Idea on that?

**Comment by evanshultz** [comment]
And I just realized the F.Fab lines were 0.12mm. Why didn't Travis flag that?

**Comment by evanshultz** [comment]
Oliver's comment about pitch determining the choice of SOIC or SSOP repo is at https://github.com/KiCad/Housings_SOIC.pretty/pull/22.

And here is the discussion about omitting the pad on the bottom: https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/47. Regardless of the choice of no bottom copper, optional bottom copper, only add it if the datasheet includes it, etc., this should be captured in KLC since it's not.

**Comment by evanshultz** [comment]
To make sure I didn't leave out any information: I didn't include any mask over the vias on these footprints. I've found that via tenting is more of a manufacturing process issue. Some solders and processes require tenting, and others don't lose solder through the vias without tenting. My feeling was that the user could easily add a patch of mask over the vias if they wanted, and so leaving it off is the best way. What do you guys think? Do we want to tent the vias in the footprint?

**Comment by SchrodingersGat** [comment]
I think that as the point of the thermal vias is to wick away heat, then it does make sense to have the bottom pad. We should not go too far down the road of thinking of every combination of user requirements. In the end, if a user needs a very specific footprint, they should either make their own or adapt the "generic" one in the libraries. 

So, we should mandate that for thermal vias, a pad is provided on the bottom copper layer. The size of this pad can always be changed by the user in the PCB design.

Regarding vias, I think we should leave them standard (for the same reasons as above). Also, IIRC, when you plot the PCB that's where you have the option to tent/untent vias. So even if there's a mask layer over the top, won't the vias "poke through" anyway because the mask is automatically pulled back around vias if the "tent vias" option is selected.

**Comment by SchrodingersGat** [comment]
Thanks for taking the time to think these issues through so thoroughly. It's very important. I'll try to make sure the KLC is updated to match whatever is decided here, but am **super** busy right now :)

**Comment by evanshultz** [comment]
@jkriege2 @poeschlr 
What do you all think about bottom copper?

I still think leaving it off is best, since if the user chooses the via footprint they should know to review this. And the non-via option is in the library if they don't want to do bottom copper.

One option would be to copy the top copper to the bottom.

I think a better way would be to define bottom copper surrounding the vias and extending out a small amount. Perhaps 0.25mm past the extents of the via annular rings. That way, we ensure all the vias are connected by copper but we don't consume any routable area on the bottom that isn't necessary.

Are there other options?

Regarding tenting, I've typically placed mask over the vias and then used a note on a fab drawing to indicate that I want the vias tented. But when I look at the docs again, perhaps the intent is to define the stencil openings. The crosshatched areas are called "soldering area", so maybe I'm misinterpreting it as mask. What do you think?
image

**Comment by jkriege2** [comment]
About the tenting (as a non-expert): You mean covering the via with solder-stop varnish? I think that would make sense for the bottom layer ... one could (IMHO) also think about filling the vias to improve heat-conductivity from top to bottom ...

Best,
JAN

**Comment by jkriege2** [comment]
About the bottom pad: I would like to have it, as the thermal vias do not make much sense without it (the amount of copper, i.e. its heat capacity inside the vias is so small that they won't have a significant effect without the bottom pad). IMHO we should have a pad simply connecting the vias, or copying the top-pad (either way is fine for me), as this provides at least a little bit of bottom copper and cooling + makes it easier to make it into a larger area. If one really doesn't need it, it's usually easier to delete something, than havong to learn/think how to get it there in the right way.

JAN

**Comment by evanshultz** [comment]
Filling vias is called "plugging". I find this specified as a fab note/option, but maybe my experience isn't representative of the whole industry. Tenting and plugging both prevent wet solder from passing through the vias and preventing good soldering of the thermal pad, but plugging is usually more expensive but gives better heat transfer.

I understand about bottom copper and have used PCB copper to cool ICs in numerous ways in production equipment. No need to repeat the same text over again.

Copying the top copper doesn't make sense to me as I wrote above. If the vias are consuming real estate on the bottom of the PCB, then I don't feel bottom copper should take up even more room. A minimal pad on the bottom to cover the vias will still give the user the most routing area on the bottom. That's what I've done here.
image

**Comment by evanshultz** [comment]
If this is OK, let me know and I'll finish the footprints in the other PR similarly.

Here is draft text for this situation in KLC, plus one other update that is related to thermal pads. Please comment and refine.
```
7.7 Footprints that have multiple copper elements that are connected need special attention.
    i. Multiple pads that are physically connected should all have the same pin number. <existing image>
    ii. Thermal vias, if present, should share the same pad number as the thermal pad on F.Cu.
    iii. When thermal vias are present, a pad on B.Cu must be added. The pad size will touch the outer extents of all thermal via annular rings plus 0.5mm margin.
    iv. The bottom thermal pad should also have B.Mask layer turned on so the bottom copper pad will be exposed. <image above>

8.3 Pad construction for SMT has two main types:
    i. Thermal pads which have specific stencil openings will use these pad layer settings:
        a. Front copper (F.Cu) and Front mask (F.Mask) for the large copper pad, with the pad number.
        b. Front paste (F.Paste) openings as required by the datasheet within the pad above, having no pin number.
    i. Normal pads for pin/lead connections will have these pad layer settings:
        a. Front copper (F.Cu)
        b. Front Mask (F.Mask)
        c. Front paste (F.Paste)
```

**Comment by jkriege2** [comment]
Fine with me now!

Best & thanks,
JAN

**Comment by evanshultz** [comment]
@jkriege2 Thank you.

@SchrodingersGat See the proposed KLC text above.

**Comment by SchrodingersGat** [comment]
Thanks @evanshultz I have updated the KLC with said changes.

**Comment by SchrodingersGat** [comment]
We also need to update the scripts to catch the 8.3 requirements (layers for special stencil design). That rule is currently throwing a lot of false negatives

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks!
- 7.7 and 7.7.i seem to be near copies. I wrote unique text above to differentiate them. Is this intentional?
- 7.7.iii does not mention this pad requires B.Mask also.
- 7.7.iii could benefit from the image above??
- 8.3.ii.b does not mention that the F.Paste pads should not have a pad number.

**Pull request merged**
