### PR TITLE
Added SOIC-16-WB

### PR DESCRIPTION
**Pull request by greenscreenflicker**
Added SOIC-16 WB.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@greenscreenflicker can you explain the differences between this footprint and **SOIC-16_7.5x10.3mm_Pitch1.27mm**? 

Your footprint has slightly longer pads, is this the only substantial difference?

**Comment by greenscreenflicker** [comment]
@SchrodingersGat :+1: You are right. It's the same footprint. Didn't see that. Can we change the nomenclature of the hole Housing SOIC, etc. lib to standardised footprint names: SOIC-16-WB not, SOIC-16_dimension, so that the names are the same as the names used in datasheets. This nomenclature keeps confusing me for this Housing_library-series.

**Comment by SchrodingersGat** [comment]
I have submitted a PR here https://github.com/KiCad/Housings_SOIC.pretty/pull/9 which addresses this. The package dimensions remain, but the **W** suffix has been added to differentiate the SOIC_16W part

**Comment by greenscreenflicker** [comment]
I think we can close this pull request.

**Pull request closed without merging**
